#!/usr/bin/env zsh

#
# .zprofile
#
# This gets loaded for login shells and interactive shells
#
# https://github.com/mattmc3/zdotdir/blob/main/.zprofile
#

# # https://github.com/zimfw/asdf/blob/master/init.zsh
# if (( ! ${+ASDF_DIR} )); then
#   for ASDF_DIR in \
#     {/usr/local,/opt/homebrew,/home/linuxbrew/.linuxbrew/}/opt/asdf/libexec \
#     /opt/asdf-vm \
#     ${HOME}/.asdf
#   do
#     if [[ -e ${ASDF_DIR} ]] break
#   done
# fi
# export ASDF_DIR
